//
//  PraxsStyleKit.swift
//  Praxs
//
//  Created by Denis Ricard on 2017-04-16.
//  Copyright © 2017 Hexaedre. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

import UIKit



class PraxsStyleKit: NSObject {
    
    
    //MARK: - Colors
    
    static let nightContextColor = UIColor(hue: 0.548, saturation: 0.324, brightness: 0.424, alpha: 1)
    static let morningContextColor = UIColor(hue: 0.098, saturation: 0.572, brightness: 0.925, alpha: 1)
    static let commuteContextColor = UIColor(hue: 0.157, saturation: 0.595, brightness: 0.949, alpha: 1)
    static let workContextColor = UIColor(hue: 0.231, saturation: 0.495, brightness: 0.761, alpha: 1)
    static let eveningContextColor = UIColor(hue: 0.551, saturation: 0.313, brightness: 0.902, alpha: 1)
    static let contextNameColor = UIColor(hue: 0.54, saturation: 1, brightness: 0.847, alpha: 1)
    
    
}
